version: '3.5'

services:
  front:
    container_name: doo-re-front
    build:
      context: ./docker
      dockerfile: front.dockerfile
    ports:
      - 3001:3001
    environment:
      - PORT=3001

  app:
    container_name: doo-re-app
    image: doo-re-app:${ENV}
    ports:
      - 80:8080 # 수정 필요
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - db

  db:
    container_name: doo-re-db
    image: doo-re-db:${ENV}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  
  nginx:
    container_name: nginx
    image: doo-re-nginx:${ENV}
    volumes:
      - ./docker/data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/nginx/conf.d:/etc/nginx/conf.d
    prots:
      - 80:80
      - 443:443